spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
    open-in-view: false
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
